### ISSUE TITLE
Components and page: Portfolio

### ISSUE THREAD

**Issue by justchrister** [justchrister/kalt#91]
## Purpose

For users to get a quick insight into how much their investments are currently worth, and the impact it has made. It should inspire further investments, and sharing it with family and friends. 

It's calculated based on buy orders in the exchange service, and the any amount in the accountBalance service. 

## To-do
- [ ] Design portfolio page
- [ ] Component: chart with filters (component)
- [ ] Calls to action (increase your subscription, invest some more etc)
- [ ] Co2 Calculations (3 cars, planerides etc) with beautiful illustrations

### Error handling

If there are no values in the table for the actual 
### Decoupling

Save the values to its own supbase table

## Wireframes
1. Chart
2. Number that is ticking upward
3. Data filters
4. Manage reoccurring payments
5. Illustrations of the environmental impact

## API
We need to create a microservice (based on standard scaffolding) that lets you:
1. getPortfolioValue (from date, to date, (if null send latest value), interval=hours, days, weeks, months, quarters, includeForecast, forecastDays (forecast should do a call to getPortfolioForecast))
2. getPortfolioForecast (based on average returns from
